alias bi='brew install'
alias bci='brew cask install'
alias br='brew remove'
alias bcr='brew cask remove'
alias bu='brew upgrade && brew cask upgrade && brew cleanup'
alias bcu='brew cu -af && brew cleanup'
alias bcl='brew cleanup'
alias zedit='vim ${HOME}/.zshrc'
alias vedit='vim ${HOME}/.vimrc'
alias path='echo $PATH | tr ":" "\n"'
alias clean='noglob sudo rm -rf /private/var/log/asl/* && rm -rf ${HOME}/Library/Developer/Xcode/DerivedData/*'
alias rmds='find $PWD -name ".DS_Store" -type f -delete -print'
alias getkerneldump='log show --debug --last boot --debug --predicate "process == \"kernel\""'
alias cs='codesign -f -s - --deep'
alias compfix='compaudit | xargs chmod g-w'
