alias bi='brew install'
alias br='brew remove'
alias bci='brew cask install'
alias bcr='brew cask remove'
alias bu='brew upgrade && brew cleanup'
alias bcu='brew cask upgrade && brew cu -af && brew cleanup'
alias bcl='brew cleanup'
alias zedit='vim $HOME/.zshrc'
alias vedit='vim $HOME/.vimrc'
alias pathlist='echo $PATH | tr ":" "\n"'
alias speedupterm='noglob sudo rm -rf /private/var/log/asl/*'
alias getkerneldump='log show --debug --last boot --debug --predicate "process == \"kernel\""'
alias delds='find $PWD -name ".DS_Store" -type f -delete -print'
alias cs='codesign -f -s - --deep'
alias compfix='compaudit | xargs chmod g-w'
