alias ls='gls -G --color'
alias python='python3'
alias pip='pip3'
alias bi='brew install'
alias br='brew remove'
alias bs='brew search'
alias bf='brew info'
alias bu='brew upgrade && brew upgrade --cask && brew cu -ay && brew autoremove && brew cleanup && brew doctor'
alias bcl='brew cleanup --prune=all'
alias gcl='git clone'
alias pathlist='echo $PATH | tr ":" "\n"'
alias speedtty='noglob sudo rm -rf /private/var/log/asl/*'
alias flushdnscache='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias zshreload='omz reload'
alias codesig='codesign -f -s - --deep'
alias compfix='compaudit | xargs chmod g-w'
alias xdropen='open ${HOME}/Library/Developer/Xcode/DerivedData'
alias getkerneldump='log show --debug --last boot --debug --predicate "process == \"kernel\""'
alias mountefi="sudo diskutil mount $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path | sed 's/.*GPT,\([^,]*\),.*/\1/')"
alias termbin='nc termbin.com 9999'
alias dotedit='mate ${HOME}/Documents/Repos/dot-files'
alias nmap='sudo grc nmap'

