alias python='python3'
alias pip='pip3'
alias bi='brew install'
alias br='brew remove'
alias bif='brew info'
alias bs='brew search'
alias bu='brew upgrade && brew upgrade --cask && brew cu -ay && brew autoremove && brew cleanup && brew doctor'
alias dotedit='mate ${HOME}/Documents/Repos/dot-files'
alias pathlist='echo $PATH | tr ":" "\n"'
alias speedtty='noglob sudo rm -rf /private/var/log/asl/*'
alias rmdsstore='find $PWD -name ".DS_Store" -type f -delete -print'
alias getkerneldump='log show --debug --last boot --debug --predicate "process == \"kernel\""'
alias codesign='codesign -f -s - --deep'
alias compfix='compaudit | xargs chmod g-w'
alias xdropen='open ~/Library/Developer/Xcode/DerivedData'
alias termbin='pbpaste | nc termbin.com 9999 | pbcopy && pbpaste'
alias mountefi="sudo diskutil mount $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:boot-path | sed 's/.*GPT,\([^,]*\),.*/\1/')"
alias flushdnscache='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
